language: python
python:
  - "3.9"
install:
  pip install -r requirements-dev.txt;
script:
  - flake8 .
  - coverage run -m pytest --ignore=lib
after_success:
  - codecov
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com
